### ISSUE TITLE
Runtimes attribute sometimes needs multiple values

### ISSUE THREAD

**Issue by stefan-kolb** [stefan-kolb/paas-profiles#102]
> Actually Nginx is used as a php and ruby app server + balancing web-server;
> Apache - as app server for php, ruby and python;
> since it is allowed to specify just a one runtime/role for each of them - I've stated the PHP one for Apache and Ruby for NGINX server. Nevertheless, it woulf be nice if you could find a way to extend their specification or allow to make dublicates.

**Comment by tirth78** [comment]
I would like to work on this issue. I am a Masters student in BITS Pilani. It would be really helpful if I could get some kind of approval from the owner/author.
