### ISSUE TITLE
Shelly Cloud offers new infrastructures and more

### ISSUE THREAD

**Issue by stefan-kolb** [stefan-kolb/paas-profiles#104]
Shelly Cloud updated their infrastructure offering, including an US offering.

@sabcio Maybe you can update the profile, if you find the time. If not, I'll do it in the next days.

**Comment by stefan-kolb** [comment]
http://us2.campaign-archive2.com/?u=047341e31b152b9eebe62bb0e&id=1fa43732a6

**Comment by sabcio** [comment]
https://github.com/stefan-kolb/paas-profiles/pull/105
