### ISSUE TITLE
Update OutSystems listing

### ISSUE THREAD

**Issue by mozzello** [stefan-kolb/paas-profiles#120]
I noticed that the OutSystems profile is missing an important piece of information regarding hosting, because the original submission had an error. 
Can you please update the OutSystems listing to have the following values in hosting:
"hosting": {"public": true, "private": true},

Thank you
Michel Ozzello

**Comment by stefan-kolb** [comment]
Hi, 
Just updated this.
If you can, it would be nice if you supply a pull request for further updates.

Thanks, Stefan

**Comment by mozzello** [comment]
Thanks for the fast response Stefan.
Sorry for not following the best process... I'm a beginner with GitHub and
am not used to the dynamics. :)

Thanks again
Michel

On Fri, Mar 20, 2015 at 10:38 AM, Stefan Kolb <notifications@github.com>
wrote:

> Hi,
> Just updated this.
> If you can, it would be nice if you supply a pull request for further
> updates.
>
> Thanks, Stefan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stefan-kolb/paas-profiles/issues/120#issuecomment-83983598>
> .
>



-- 
Michel Ozzello

*Digital Marketing Director*
OutSystems Portugal
www.outsystems.com
