### ISSUE TITLE
show if is open source or proprietary

### ISSUE THREAD

**Issue by joubertredrat** [stefan-kolb/paas-profiles#123]
isn't good idea? I want open source PaaS to test and I need to open PaaS info to see if is open source, free or proprietary.

**Comment by stefan-kolb** [comment]
Good point, I'll consider adding this information!

**Comment by stefan-kolb** [comment]
@joubertredrat If you need the information now, I've added it inside the `technologies.json` inside the referenced commit. Will add it to the UI and search functionalities later on.

**Comment by joubertredrat** [comment]
@stefan-kolb isn't better to put "license" instead of "dev_model"? Because will be possible to display if this PaaS is open source, proprietary or a service or another, as fremium, free and anothers.

Example:
Openshift Origin: => Opensource
Tsuru: => Opensource
Stackato: => proprietary
Openshift Enterprise: => proprietary
Heroku: => Service
Amazon Elastic Beanstalk: => Service

**Comment by stefan-kolb** [comment]
In my opinion what you are looking for are not "licenses". A license might be GPL, Apache or MIT.
Therefore, I chose `dev_model` for the moment (although this is not set in stone yet!).
What you are trying to achieve via `proprietary` vs `service` is already depicted by the `hosting`attribute. It's `public = service` and `private = self-hostable`

**Comment by vectornet** [comment]
@stefan-kolb I used on Alternativeto to open this issue, I think that in this case "license" isn't correct word.

Look this http://alternativeto.net/software/mobalivecd/?license=opensource
on their site "license" types is "free or open source", "only open source" and "commercial".

But now I've seen the model you actually used is the correct, dev_model.

**Comment by joubertredrat** [comment]
@stefan-kolb I used on Alternativeto to open this issue, I think that in this case "license" isn't correct word.

Look this http://alternativeto.net/software/mobalivecd/?license=opensource
on their site "license" types is "free or open source", "only open source" and "commercial".

But now I've seen the model you actually used is the correct, dev_model.
