### ISSUE TITLE
Add dimensions

### ISSUE THREAD

**Issue by OriPekelman** [stefan-kolb/paas-profiles#135]
Hi I think there are a number of interesting dimensions that could be added:
1. Integrated backup / restore:  what gets backed up.. whole cluster / db only etc.. )
2. Workflow support (managed creation of dev/staging etc..)
3. Multi-App support (Single App / App + Workers / Multi-App + Workers)
4. Acces Types (SSH? FTP? Only CLI / API ? Custom ? etc..)
5. Security  (ssl support / acces control / TFA / .. )

And maybe, though this should probably not be a factor that people care about ... some dimensions on the runtime.. VM based? Container Based? Clustered Containers? Docker? Specific OS? adherence to a Linux distribution .. Other ..  ?

**Comment by stefan-kolb** [comment]
Hi, thanks for your ideas. 
I'll consider adding some of them later on.
Especially no.4. is on the backlog.
Dimensions on the platform isolation are already included, although limited to container-based and VM-based at the moment (see https://github.com/stefan-kolb/paas-profiles/blob/master/data/technologies.json).

**Comment by OriPekelman** [comment]
Thnx;
I think the multi-app thing is also an interesting thing.. because it kind of determines how "opinionated" the paas is... is it a single monolithic web thing? Can you du micro-services? Can you deploy multiple technologies together ?
And the workflow.. dev/staging/prod thing is I think becoming a recurrent theme now (Jelastic / Bluemix .. and of course us put it forward as a strong differentiating factor)
