### ISSUE TITLE
Information on Bluemix is out of date

### ISSUE THREAD

**Issue by aairom** [stefan-kolb/paas-profiles#173]
Hi;
There are a lot of news on Bluemix, a lot of more services, new datacenter in Sydney...
Maybe the site should be updated.

**Comment by stefan-kolb** [comment]
Thanks for pointing this out! Maybe you can help to improve the information?

**Comment by aairom** [comment]
Sure, how can I help?

**Comment by stefan-kolb** [comment]
If you notice any missing or wrong data you may submit a pull request to change this information. Details are provided inside the [README](https://github.com/stefan-kolb/paas-profiles/blob/master/README.md) and the [CONTRIBUTING](https://github.com/stefan-kolb/paas-profiles/blob/master/CONTRIBUTING.md) files. You can also fork the project and edit the JSON files via Github.
