### ISSUE TITLE
Add GE's predix.io

### ISSUE THREAD

**Issue by JohannesRudolph** [stefan-kolb/paas-profiles#188]
Hi Stefan, great work at paasfinder.org and in your research, I came across quite a few of your papers 👍 

I have noticed that the PaaS Finder does not include the predix.io platform: https://www.predix.io/ 
It's a cloud foundry PaaS, very similar to Bluemix. I might come around to add a profile for it later this week, just want to open this issue to keep track of this!

**Comment by stefan-kolb** [comment]
Hi,

Thanks, glad you like it :smile: 
would be great to have a profile for Predix!
I also send an email to them a few days ago when contacting all vendors from https://www.cloudfoundry.org/use/cloud-foundry-certified/.

Cheers, Stefan

**Comment by JohannesRudolph** [comment]
Haha, did the same thing a month or two ago :-) Currently working on a
research broker for CF PaaS, so checking the vendor landscape is important.
Atos, Huawei and SAP appear to offer private PaaS only, haven't heard from
them. Did you hear from them?

**Comment by stefan-kolb** [comment]
Yeah, kind of. Like you said they only offer a CF-based private PaaS. As for SAP they are also only in beta right now.Atos updated their stuff in May or so. Did you see Nucleus (https://github.com/stefan-kolb/nucleus) when working on a broker? What kind of broker are you working on?

**Comment by JohannesRudolph** [comment]
Yes, saw Nucleus. I'm not really trying to write an Inter-Cloud broker,
 but an (empirical!) performance + criteria based broker/decision support
system to analyse some economic properties of the CF provider market. With
6+ CF public CF providers there's quite a bit on the table.

**Comment by stefan-kolb** [comment]
Yeah, you can also see them on the CF page https://paasfinder.org/vendors/cloud+foundry. But you have probably noticed that already :smile:
