### ISSUE TITLE
Type: "SaaS-Centric, Generic, IaaS Centric" is too limiting

### ISSUE THREAD

**Issue by OriPekelman** [stefan-kolb/paas-profiles#230]
Hi,

I don't really know what to put there for platform.sh it does all three.. (there are direct clients that deploy arbitrary code, we have SaaS software vendors that run their stuff on our system -- like magento.. and we have IaaS providers that use us to run their own PaaS solutions -- Azure DE, Orange France).

Would it be conceivable to change this into a multi-valued feature?

Cheers, and thanks for all the hard work!

Ori

**Comment by stefan-kolb** [comment]
Hi,

In your case it is just Generic imho.
Please see [this paper](https://www.uni-bamberg.de/fileadmin/uni/fakultaeten/wiai_lehrstuehle/praktische_informatik/Dateien/Publikationen/sose14-towards-application-portability-in-paas.pdf) for more information on the services types.

SaaS-centric often means that you can only deploy applications that are extensions of an existing SaaS solution like Salesforce CRM or very special custom tailored PaaS for Business Analytics etc.
These platforms typically do not allow you to host arbitrary app code.
--> Salesforce

Generic means you can deploy arbitrary applications to a hosted environment (PaaS) that gives you certain application dependencies like runtimes,....
--> Heroku

IaaS-centric does all that Generic does but often allows more control over the environment or even is just an orchestration of lower level IaaS components that can still be used independently from the PaaS.
--> AWS Elastic Beanstalk

Does this make sense for you?

**Comment by OriPekelman** [comment]
Yeah it makes sense .. I will keep generic (and possibly let people running "Salesforce" like PaaS based on platform.sh to make their own entries - we have Magento, Sensio and a couple of others doing that..).

**Comment by stefan-kolb** [comment]
I'm happy to find a better classification, but this is so far the best one I could come up with over the years to classify all of the different offerings termed "PaaS".
