### ISSUE TITLE
additional Providers for CloudFoundry: GE-Predix, Siemens-Mindsphere, SAP cloud platform starter edition

### ISSUE THREAD

**Issue by technet13** [stefan-kolb/paas-profiles#247]
Hey!

Sry, not too involved in Github, sry. But an issue from my side to contribute, too:
additional Providers for CloudFoundry:
(or are there meant only the pure CloudFoundry based providers?

so these at least use CloudFoundry or integrate it:

- Predix (GE): fully based on it I think
([Whitepaper page 13](https://d154rjc49kgakj.cloudfront.net/GE_Predix_Architecture_and_Services.pdf))

- Mindsphere (Siemens): only integrated, because [developed on SAP HANA before](https://www.silicon.de/41633069/sap-setzt-auch-bei-iot-auf-die-hana-cloud-platform/?inf_by=5a85866f671db8ba168b469d)
([Whitepaper page 10](https://www.plm.automation.siemens.com/media/global/en/Siemens_MindSphere_Whitepaper_tcm27-9395.pdf) or [product newsletter page 45](https://c4b.gss.siemens.com/resources/images/articles/dffa-b10429-00-00de.pdf))
(or later adopted on ClouFoundry completely, but not for sure)

- SAP Cloud Platform (at least the starter edition): (not HANA!) one edition from SAP only based on CF
([hana.ondemand](https://eaexplorer.hana.ondemand.com/_item.html?id=12453#!/relation/0))

What also would be really cool to know where to have test accounts to test developing with which specs and trials, and so on...

Greets

**Comment by stefan-kolb** [comment]
Please see https://github.com/stefan-kolb/paas-profiles/blob/master/CONTRIBUTING.md for details on how to add providers.
Concerning your request for test accounts, you an search for free and find all vendors with free pricing. Test accounts are not included yet, but nearly every vendor gives you a test account.
